### ISSUE TITLE
Deployment options for distill dev page

### ISSUE THREAD

**Issue by mitchelloharawild** [rjournal/rjournal.github.io#34]
Hosting the dev page for the 2021-1 release under an appropriate location is useful for feedback on the changes.

A few deployment options exist:

- ~~`rjournal.github.io/dev` - Either copy to directory of `master`, or maybe a different repo could work. Problem is that it exposes/advertises the `rjournal.github.io` test domain.~~
- ~~`rjournal-dev.github.io` - Requires a new organisation.~~
- ~~`rjournal-dev.r-project.org` - Ask for custom subdomain pointing to gh pages in a different distill-dev repo. This hosts distill on gh pages servers.~~
- `rjournal.r-project.org/dev` - Use gh action to take `master/` and `dev/_web` locations into publish branch. This hosts distill on CRAN servers.

**Comment by mitchelloharawild** [comment]
Simon to update the action.
Mitch to do nothing :smile: (@distill/_web to @deploy/dev)
Di to update the 2021-1 editorial

**Comment by s-u** [comment]
Action added. I have also added support for manual workflow trigger, just make sure you use `published` branch when manually initiating the trigger.

**Comment by mitchelloharawild** [comment]
Deployed at `journal.r-project.org/dev`.
