### ISSUE TITLE
List of pdfs in past articles not appearing

### ISSUE THREAD

**Issue by dicook** [rjournal/rjournal.github.io#78]
-  The two Help Desk articles in https://journal.r-project.org/archive/2011-1/ are missing pdfs.

**Comment by mitchelloharawild** [comment]
Resolved by 6a03e6c9b0ee2c5fbafc2800e0e504ad25bebcf3.
https://rjournal.github.io/news/RJ-2011-1-Hyndman/
https://rjournal.github.io/news/RJ-2011-1-Cook/
